---
driver:
  name: vagrant
  gui: true

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: windows2012r2-windowsonly

suites:
  - name: default
    run_list:
      - recipe[seq::default]
    attributes:
