---
driver:
  name: vagrant
  gui: true

provisioner:
  name: chef_zero

platforms:
  - name: windows2012r2-windowsonly
    transport:
      name: winrm
      elevated: true

suites:
  - name: local
    run_list:
      - recipe[seq::default]
    attributes:
      seq:
        source: http://10.0.1.31:8888/Seq-3.1.17.msi
      ms_dotnet:
        v4:
          version: '4.5.2'
          package_sources:
            '6c2c589132e830a185c5f40f82042bee3022e721a216680bd9b3995ba86f3781': 'http://10.0.1.31:8888/NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
